name: Cron Workflow
on:
  workflow_dispatch:

env:
    DOCKER_USERNAME: njavalgi
    DOCKER_PASS: M4a1carbine
    CONTAINER_REG: docker.io
    IMAGE_NAME: nginx-ingress
jobs:
    cron-job:
        runs-on: ubuntu-latest
        steps:
         -  name: Docker pull
            run: echo docker pull ${{env.CONTAINER_REG}}/nginx/${{env.IMAGE_NAME}}

         - name: docker login
           run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASS}}

         - name: docker push
           run: echo docker push ${{env.CONTAINER_REG}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest