name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo  
            run: actions/checkout@v4
            
          - name: Welcome Message
            run: echo "Hello,Ya Idiot!"

          - name: List Files
            run: ls

          - name: End Message
            run: echo "See Ya!"