name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo  
            uses: actions/checkout@v4

          - name: Welcome Message
            run: echo "Hello,Ya Idiot!"

          - name: List Files and Read files
            run: |
              ls
              cat README.md
        
          - name: Execute shell file
            run: |
                chmod +x ./workflows/ascii-shell.sh
                ./ascii-shell.sh

          - name: End Message
            run: echo "See Ya!"