name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo  
            uses: actions/checkout@v4

          - name: Install Cowsay
            run: sudo apt-get install -y cowsay

          - name: Welcome Message
            run: echo "Hello,Ya Idiot!"

          - name: List Files and Read files
            run: |
              ls
              cat README.md

          - name: Generate ASCII Artwork
            run: cowsay -f dragon "I am Dragon tung tung tung sahuur" >> dragon.txt
        
          - name: List Dragon File
            run: ls -lrt | grep dragon.txt

          - name: End Message
            run: echo "See Ya!"